// Automatically generated by astro-icon
// 0f67cd0c3cb8def8a21b789830cb892e57f1f6dc4942abb62c6242b146f8ad10

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "at"
		| "book"
		| "bookmark"
		| "bookmark-solid"
		| "clock"
		| "comment"
		| "github"
		| "heart"
		| "home"
		| "link"
		| "location"
		| "logo"
		| "mastodon"
		| "moon"
		| "refresh"
		| "rss"
		| "share"
		| "sun"
		| "twitter";
}